# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740f9c180222fbd12ae96ce20c0f6207ee956fd6690812038bd45a520e034d192a675bb0ba8fcbd842fd3b97ecf7b0a131187e52afa0161e595640b2d4d98a53

test:
  secret_key_base: 59a9236ec920f1c3f102c1f8a633d3b57d5413cb60bc92c801f8fe781f9cf25975ec1c41d445cf3ef700ab0d7dd41022413650b2c499f44070bb607d18b6ac0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
